### ISSUE TITLE
TA comments

### ISSUE THREAD

**Issue by slumnitz** [UBC-MDS/DSCI532_Group204_Vino#28]
Yes please make one for BC too? Or a world wide one? Can one distinguish between red and white? :)

Keep it up, this is a great app and a well written proposal and designed sketch!

IMPORTANT: Make sure to divide work and commits equally!

Keep your commit messages informative (try answer: What exactly did you update/ change?), communicate via issues, or even check out the GitHub project functionality!

**Comment by jnederlo** [comment]
Noted and considered!
