### ISSUE TITLE
Fix axis label angles on heatmap plot

### ISSUE THREAD

**Issue by brendoncampbell** [UBC-MDS/DSCI532_Group204_Vino#77]

**Comment by brendoncampbell** [comment]
Having issues with this fix: the theme change specifically for this heatmap gets overriden by the theme for the other plot on this tab of the app. Low priority

**Comment by jnederlo** [comment]
This is not so much a bug as it is a feature request. Theme provides readability, so no fix necessary. Agree with Low Priority.

**Comment by brendoncampbell** [comment]
Fixed
